services:
  frontend:
    image: louisburress/coach_qoiya.frontend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - webnet

  backend:
    image: louisburress/coach_qoiya.backend:latest
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - webnet

  nginx:
    image: louisburress/coach_qoiya.nginx:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - webnet

networks:
  webnet:

