services:
  frontend:
    image: louisburress/coach_qoiya.frontend:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    image: louisburress/coach_qoiya.backend:latest
    ports:
      - "5000:5000"
    restart: unless-stopped

