version: '3'
services:
  frontend:
    build:
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend-app:/app
      - /app/node_modules  # Avoid overwriting node_modules in container
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
  backend:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend-app:/app  # Correct path to backend folder
      - /app/node_modules  # Avoid overwriting node_modules in container

