name: Deploy Application to AWS EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        run: |
          docker build -t louisburress/coach_qoiya.frontend:latest ./frontend-app
          docker build -t louisburress/coach_qoiya.backend:latest ./backend-app
          docker push louisburress/coach_qoiya.frontend:latest
          docker push louisburress/coach_qoiya.backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}  # Adjusted to use a secret for username
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            git pull origin main  # Ensure the latest changes are pulled
            docker-compose down  # Stop current containers
            docker-compose up -d  # Start containers using the docker-compose.yml in the root
