name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend-app
          file: ./frontend-app/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.frontend:latest
          push: true

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend-app
          file: ./backend-app/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.backend:latest
          push: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Clone the repository
            git clone git@github.com:louisburress/coach_seqoiya.git .
            # Ensure Docker is running
            sudo systemctl start docker
            sudo usermod -aG docker $USER
            # Pull the latest Docker images
            docker pull ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.backend:latest
            # Start the application using Docker Compose
            docker-compose down
            docker-compose up -d
