name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./frontend-app
          file: ./frontend-app/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.frontend:latest
          push: true

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend-app
          file: ./backend-app/Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.backend:latest
          push: true

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with docker-compose
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo docker-compose down
            sudo docker-compose up -d

