name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Check out your repository into the GitHub Actions runner

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend-app
          file: ./frontend-app/Dockerfile
          push: true
          tags: louisburress/coach_qoiya.frontend:latest

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend-app
          file: ./backend-app/Dockerfile
          push: true
          tags: louisburress/coach_qoiya.backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  # Ensure the repository content is available for the deploy step

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > docker-compose.yml  # Create docker-compose.yml on the VM
            docker-compose pull  # Pull the latest images
            docker-compose up -d  # Deploy containers in detached mode

