name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Building the Docker image
    - name: Build the Docker image
      run: |
        docker build -t louisburress/coach_qoiya:v1 .

    # Logging into DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Pushing the Docker image to DockerHub
    - name: Push Image to DockerHub
      run: |
        docker push louisburress/coach_qoiya:v1

    # Deploying to AWS EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull louisburress/coach_qoiya:v1
          docker-compose up -d


