name: Deploy Application to AWS EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to log in to DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Images
      - name: Build and Push Docker Images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.frontend:latest ./frontend-app
          docker build -t ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.backend:latest ./backend-app
          docker push ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest Docker images
            docker pull ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.frontend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/coach_qoiya.backend:latest

            # Navigate to where the docker-compose.yml file is located
            # If it's in the root, no need to change directories.
            docker-compose down
            docker-compose up -d

